# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

require 'fileutils'
require 'xcodeproj'
require 'yaml'

fastlane_version "1.99.0"

# make sure to always end version string with ".0". E.g. "13.1.0" instead of "13.1" to ensure that not "13.2" gets used
xcodes(version: "26.2.0", select_for_current_build_only: true)

default_platform :ios

before_all do
  ENV["FASTLANE_ITC_TEAM_ID"] = "53UHVFU34J"

  ensure_git_status_clean
  branch = git_branch
  git_pull

  sentry_check_cli_installed()

  api_key = app_store_connect_api_key(
    key_id: "355BAH87A6",
    issuer_id: "69a6de7b-759e-47e3-e053-5b8c7c11a4d1",
    key_filepath: "./fastlane/AuthKey_355BAH87A6.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )
end

desc "Build and upload SwiftLinTest iOS"
lane :ios do
  orgSlug = 'appmonkey'
  projectSlug = 'swiftlint-pr-test'

  version = get_version_number(target: "swiftlint-pr-test")
  buildNumber = number_of_commits.to_s

  gym(
    scheme: "swiftlint-pr-test",
    configuration: "Release",
    include_symbols: true,
    export_method: "app-store",
    export_options: {
      provisioningProfiles: {
        "com.appmonkey.swiftlintprtest" => "swiftlintprtest distribution"
      }
    },
    xcargs: "-skipPackagePluginValidation"
  )
  begin
    pilot(
      ipa: "build/swiftlintprtest.ipa",
      changelog: YAML.load_file('testflight_changelog.yml')["en-US"],
      beta_app_description: YAML.load_file('testflight_beta_app_description.yml')["en-US"],
      distribute_external: true,
      groups: "Internal",
      reject_build_waiting_for_review: false
    )
  rescue Exception => e
    if e.message.include? "Another build is in review"
      UI.important("Another build is already in external beta review. Skipping external beta review submission")
    elsif e.message.include? "The resource 'betaAppReviewSubmissions' does not allow 'DELETE'"
      UI.message("Removing existing build from review failed.")
    else
      raise
    end
  end

  changeLog = changeLog(app: "ios")

  originalBranchName = git_branch

  set_github_release(
    repository_name: "mubi/ios",
    tag_name: "builds/iOS/" + version + "-" + buildNumber,
    name: "iOS " + version + "-" + buildNumber,
    description: changeLog,
    is_prerelease: true,
    commitish: last_git_commit[:commit_hash]
  )

  if originalBranchName == "master" # don't create release branches for hotfixes
    sh("git checkout -b releases/iOS/" + version + "-" + buildNumber)
    push_to_git_remote()
    sh("git checkout " + originalBranchName)
  end

  slack(
    message: "New iOS TestFlight version #{version} (#{buildNumber}) incoming!",
    default_payloads: []
  )
end
