name: SwiftLint PR Check
on:
  pull_request:
    paths:
      - '**/*.swift'

permissions:
  pull-requests: write
  contents: read

jobs:
  lint:
    name: SwiftLint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check swift codestyle
      uses: cirruslabs/swiftlint-action@v1
      with:
        args: --path ${{ steps.changes.outputs.files }} --config .swiftlint.yml --strict
